#!/bin/bash

if [ -d ./python3env ]
then
  source ./python3env/bin/activate
else
  python3 -m venv python3env
  source ./python3env/bin/activate
  pip install --no-cache-dir --upgrade pip
  pip install --no-cache-dir -r requirements.txt
fi

python3 'bridge2.py'
deactivate